package com.example;

public enum TokenType {
    // Keywords
    CITY, DISTRICT, ZONE,  TRAFFICLIGHT, STREET,
    UNDERCONSTRUCTION, NEWLYPAVED, OLD, DAMAGED, CURVE, ROUNDABOUT,
    BUILDING, POOL, GYM, ROOFTOPACCESS, PARK, INFRASTRUCTURE, RIVER, LAKE,
    RESTAURANT, EVENT, FESTIVAL, PARADE, FARMERS_MARKET, UTILITY,
    POWERPLANT, WATERTREATMENT, MONUMENT, RESIDENTIAL, COMMERCIAL, INDUSTRIAL,
    BRIDGE, TUNNEL, AIRPORT, TRANSPORT, ATTRACTION,

    IDENTIFIER,

    // Operators
    LPAREN, RPAREN, LBRACE, RBRACE, COMMA, SEMICOLON, LBRACKET, RBRACKET,

    // Literals
    STRING, INTEGER, FLOAT,

    // Special tokens
    EOF, UNKNOWN
}