name: Docker build and webhook trigger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker web image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: zanderanja/outsiders:qnaimage

  send-webhook:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_type: 'json'
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
          webhook_headers: '{"Content-Type": "application/json"}'
